[project]
name = "LLMmap"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "litellm>=1.80.11",
    "pandas>=2.3.3",
    "rich>=14.2.0",
    "tenacity>=9.1.2",
]
